#!/usr/bin/env bash

# ***This script was made by Clay Gomera (Drake) and modified by Moss Gallagher (mosswg)***
#  - Description: A simple wallpaper changer script
#  - Dependencies: rofi, fd, hyprpaper

## MAIN VARIABLES AND COMMANDS ##
walldir="$HOME/wallpapers/" # wallpapers folder, change it to yours, make sure that it ends with a /
cd "$walldir" || exit

## SELECT PICTURE FUNCTION ##
selectpic() {
    wallpaper=$(fd -p "$walldir" | rofi -dmenu -l 10 -b -i -p "Select a wallpaper:")
    if [ "$wallpaper" ]; then
        chosenwall=$wallpaper
    else
        exit 0
    fi
}
selectpic

## WALLPAPER SETTING OPTIONS ##
option1="Fill"
option2="Center"
option3="Tile"
option4="Max"
option5="Scale"
options="$option1\n$option2\n$option3\n$option4\n$option5"

## MAIN ACTION ##
echo "$walldir$chosenwall";
hyprctl hyprpaper preload "$walldir$chosenwall";
hyprctl hyprpaper wallpaper eDP-1,"$walldir$chosenwall";
exit 0
