#!/bin/bash
layout=$(setxkbmap -query | grep -oP 'layout:\s*\K\w+');
variant=$(setxkbmap -query | grep -oP 'variant:\s*\K\w+');

if [ -n "$variant" ];
then
	echo " $layout - ${variant:0:2}" | tr '[:lower:]' '[:upper:]';
else
	echo " $layout" | tr '[:lower:]' '[:upper:]';
fi
